# Generated by Django 5.2.8 on 2026-01-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_category_cloth_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='is_available',
        ),
        migrations.AddField(
            model_name='cloth',
            name='categories',
            field=models.ManyToManyField(related_name='clothes', to='app1.category'),
        ),
    ]
