# Generated by Django 5.2.8 on 2026-01-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rentrequest_total_days_rentrequest_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentrequest',
            name='buyer_requested_pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
