# Generated by Django 5.2.8 on 2026-01-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_rentrequest_buyer_requested_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentrequest',
            name='payment_mode',
            field=models.CharField(default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='rentrequest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
