# Generated by Django 5.2.8 on 2026-01-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rentrequest_payment_mode_rentrequest_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
